# Generated by Django 5.1.3 on 2024-11-20 21:46

import currency.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCode', models.CharField(max_length=3, unique=True, verbose_name='NumCode')),
                ('CharCode', models.CharField(max_length=3, unique=True, verbose_name='CharCode')),
                ('Nominal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nominal')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('Value', models.FloatField(validators=[currency.models.validate_positive], verbose_name='Value')),
                ('Previous', models.FloatField(validators=[currency.models.validate_positive], verbose_name='Previous')),
            ],
        ),
    ]
