# Generated by Django 5.1.3 on 2024-11-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='UID',
            field=models.CharField(max_length=10, null=True, verbose_name='UID'),
        ),
    ]
