# Generated by Django 5.1.3 on 2024-11-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_remove_currency_id_currency_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='UID',
            field=models.CharField(max_length=10, unique=True, verbose_name='UID'),
        ),
    ]
